name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        go:
          - "1.22"
          - "1.23"
          - "1.24"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Run go version
        run: |
          go version
      - name: Run go vet
        run: |
          go vet ./...
      - name: Run go test
        run: |
          go test -cover -v -race ./...
